version: '3'
services:
  view:
    build: ./
    command: sh -c "cd /app && yarn dev" 
    container_name: 'VIEW'
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
